export const symptomsList = [
    "abdominal pain", "aching all over", "always cold", "always going to the bathroom", "always hot",
    "always hungry", "always thirsty", "anxious", "apathetic", "arm weakness",
    "arrhythmia", "barfing", "bathroom constantly", "beating pain", "bed soaked",
    "belly pain", "bleeding nose", "bleeding skin", "blind in one eye", "blinding headache",
    "blocked nose", "blood cough", "blood in urine", "bloodshot eyes", "bloody nose",
    "bloody pee", "bloody spit", "blurred vision", "blurry eyes", "body ache",
    "body aches", "body hurts", "boob hurts", "bored of everything", "brain fog",
    "breast grew", "breast lump", "breast pain", "breast shrank", "breathless",
    "brown pee", "bump in breast", "bumps on skin", "burning skin", "burning up",
    "can't bend", "can't breathe", "can't breathe through nose", "can't focus", "can't hold it",
    "can't lift arm", "can't move well", "can't see", "can't see clearly", "can't sit still",
    "can't sleep", "can't smell", "can't stand lights", "can't stay awake", "can't stop eating",
    "can't talk right", "can't taste", "change in breast size", "change in vision", "chest hurts",
    "chest pain", "chest pressure", "chest tightness", "chills", "chronic cough",
    "chronic fatigue", "clay colored poop", "confused", "confusion", "congestion",
    "constant bathroom", "cough", "cough with phlegm", "cough won't go away", "coughing",
    "coughing blood", "coughing for weeks", "coughing up mucus", "cracked skin", "crooked smile",
    "crying", "crying a lot", "crying eyes", "dark pee", "dark urine",
    "dented nails", "depressed", "difficulty breathing", "difficulty concentrating", "discharge from eye",
    "disoriented", "distracted", "dizziness", "dizzy", "don't care",
    "don't know where i am", "down", "drained", "drinking lots of water", "droopy face",
    "dry cough", "dry cracked skin", "dry mouth", "dry skin", "edema",
    "edgy", "exhausted", "extreme fatigue", "extreme hunger", "eye crust",
    "eyes hurt behind", "eyes watering", "face drooping", "faint", "fatigue",
    "fear", "feeble", "feel sick", "feel worthless", "feeling cold",
    "feeling warm", "feeling weak", "feels itchy", "feels like dirt in eye", "fever",
    "fidgety", "flaky skin", "fluid from nipple", "fluttering heart", "food tastes bland",
    "freezing", "frequent urination", "fuzzy vision", "gained weight", "gasping",
    "giving up", "going bald", "goiter", "gritty feeling in eye", "gunky eyes",
    "gut pain", "hacking", "hair falling out", "hair loss", "half face paralyzed",
    "hard breathing", "hard mass in breast", "hard to breathe", "hard to walk", "hate cold",
    "hate heat", "head hurts", "head pain", "head splitting", "headache",
    "heart hurts", "heart pounding", "heart racing", "heart skipping", "heaving",
    "heavy chest", "high fever", "hives", "hoarseness", "holes in nails",
    "hopelessness", "hot flashes", "hot joints", "increased thirst", "inflamed",
    "insomnia", "irregular heartbeat", "itching", "itchy", "itchy eyes",
    "jaundice", "jaw aching", "jaw hurts", "joint pain", "joints ache",
    "keep sneezing", "knees hurt", "knot in breast", "leaking nipple", "light grey stool",
    "light sensitivity", "lightheaded", "lights hurt eyes", "limited movement", "look white",
    "looking yellow", "loose stools", "losing hair", "losing voice", "loss of interest",
    "loss of smell", "loss of taste", "lost weight", "low fever", "low-grade fever",
    "lower stomach hurts", "lump in neck", "migraine", "mild fever", "mumbling",
    "muscle pain", "muscles ache", "muscles hurt", "nasal drip", "nausea",
    "neck hurts", "nervous", "nervousness", "night sweats", "nipple discharge",
    "no color", "no energy", "no hope", "no smell", "no strength",
    "no taste", "noisy breathing", "nose flowing", "nosebleed", "numb arm",
    "out of breath", "pain behind eyes", "pain in belly", "pain in breast", "pain in heart",
    "pain in jaw", "pain in joints", "pain in neck", "pain swallowing", "pale face",
    "pale skin", "pale stool", "palpitations", "panicked", "peeing a lot",
    "peeing less", "peeing more", "persistent cough", "perspiring", "photophobia",
    "pink urine", "pitted nails", "pounding head", "pressure behind eyes", "productive cough",
    "puffy", "puffy legs", "puking", "pulsating pain", "pus in eye",
    "queasy", "rapid heartbeat", "rash", "raspy voice", "red eye",
    "red marks", "red patches of skin", "red pee", "red rash", "red skin",
    "red spots", "redness", "redness in eye", "reduced motion", "restlessness",
    "room spinning", "runny nose", "runs", "sad", "sadness",
    "sand in eye", "scales", "scaly skin", "scared", "scratching",
    "scratchy throat", "scratchy voice", "seeing spots", "severe fever", "severe headache",
    "severe muscle aches", "shivering", "shortness of breath", "sick to my stomach", "silvery scales",
    "skin feels hot", "skin hurts", "sleep problems", "sleepy", "slightly hot",
    "sluggish", "slurred speech", "sneeze a lot", "sneezes", "sneezing",
    "sniffles", "sore muscles", "sore throat", "speech difficulty", "starving",
    "sticky eyes", "stiff", "stiff joints", "stiff neck", "stiffness",
    "stinging skin", "stomach ache", "stomach cramps", "stomach hurting", "stressed",
    "struggling for air", "stuffed up", "stuffy nose", "super dry skin", "super tired",
    "sweating", "sweating in sleep", "sweaty", "swelling", "swelling legs",
    "swelling neck", "swollen", "swollen ankles", "tea colored pee", "tearing",
    "teary", "teary eyes", "temp 102", "temp over 100", "temperature sensitivity",
    "tender breasts", "terrified", "thick neck", "throat hurts", "throat pain",
    "throbbing pain", "throwing up", "tight chest", "tight muscles", "tired",
    "trouble seeing", "trouble sleeping", "tummy ache", "uneven breasts", "urination changes",
    "very hot", "vision blacked out", "vision loss", "vision problems", "visual changes",
    "vomiting", "waking up a lot", "waking up drenched", "want to throw up", "warm joints",
    "warm knees", "watery diarrhea", "watery eyes", "weak arm", "weakness",
    "weary", "weight changes", "weight dropping", "weight loss", "wet cough",
    "wheezing", "whistling breath", "white poop", "worried", "worst headache",
    "yellow eyes", "yellow skin",
];

export const examples = [
    "chest pain shortness of breath sweating",
    "frequent urination increased thirst fatigue",
    "persistent cough night sweats weight loss",
    "joint pain swelling stiffness",
    "sadness hopelessness sleep problems fatigue"
];
